import { createEsmwell } from '/esmwell/index.mjs'

const modules = [
  'Array',
  'BigDecimal',
  'BigInt',
  'Boolean',
  'Brand',
  'Cache',
  'Cause',
  'Channel',
  'ChannelSchema',
  'Chunk',
  'Clock',
  'Combiner',
  'Config',
  'ConfigProvider',
  'Console',
  'Context',
  'Cron',
  'Crypto',
  'Data',
  'DateTime',
  'Deferred',
  'Differ',
  'Duration',
  'Effect',
  'Effectable',
  'Encoding',
  'Equal',
  'Equivalence',
  'ErrorReporter',
  'ExecutionPlan',
  'Exit',
  'Fiber',
  'FiberHandle',
  'FiberMap',
  'FiberSet',
  'FileSystem',
  'Filter',
  'Formatter',
  'Function',
  'Graph',
  'HKT',
  'Hash',
  'HashMap',
  'HashRing',
  'HashSet',
  'Inspectable',
  'Iterable',
  'JsonPatch',
  'JsonPointer',
  'JsonSchema',
  'Latch',
  'Layer',
  'LayerMap',
  'LayerRef',
  'LogLevel',
  'Logger',
  'ManagedRuntime',
  'Match',
  'Metric',
  'MutableHashMap',
  'MutableHashSet',
  'MutableList',
  'MutableRef',
  'Newtype',
  'NonEmptyIterable',
  'Number',
  'Optic',
  'Option',
  'Order',
  'Ordering',
  'PartitionedSemaphore',
  'Path',
  'Pipeable',
  'PlatformError',
  'Pool',
  'Predicate',
  'PrimaryKey',
  'PubSub',
  'Pull',
  'Queue',
  'Random',
  'RcMap',
  'RcRef',
  'Record',
  'Redactable',
  'Redacted',
  'Reducer',
  'Ref',
  'References',
  'RegExp',
  'Request',
  'RequestResolver',
  'Resource',
  'Result',
  'Runtime',
  'Schedule',
  'Scheduler',
  'Schema',
  'SchemaAST',
  'SchemaError',
  'SchemaGetter',
  'SchemaIssue',
  'SchemaParser',
  'SchemaRepresentation',
  'SchemaTransformation',
  'Scope',
  'ScopedCache',
  'ScopedRef',
  'Semaphore',
  'Sink',
  'Stdio',
  'Stream',
  'String',
  'Struct',
  'SubscriptionRef',
  'Symbol',
  'SynchronizedRef',
  'Take',
  'Terminal',
  'Tracer',
  'Trie',
  'Tuple',
  'TxChunk',
  'TxDeferred',
  'TxHashMap',
  'TxHashSet',
  'TxPriorityQueue',
  'TxPubSub',
  'TxQueue',
  'TxReentrantLock',
  'TxRef',
  'TxSemaphore',
  'TxSubscriptionRef',
  'Types',
  'UndefinedOr',
  'Unify',
  'Utils',
  'testing',
  'unstable/ai',
  'unstable/cli',
  'unstable/cluster',
  'unstable/devtools',
  'unstable/encoding',
  'unstable/eventlog',
  'unstable/http',
  'unstable/httpapi',
  'unstable/observability',
  'unstable/persistence',
  'unstable/process',
  'unstable/reactivity',
  'unstable/rpc',
  'unstable/schema',
  'unstable/socket',
  'unstable/sql',
  'unstable/workers',
  'unstable/workflow',
] as const

const batchSize = 24
for (let start = 0; start < modules.length; start += batchSize) {
  const batch = modules.slice(start, start + batchSize)
  test(`loads Effect v4 beta core modules ${start + 1}-${start + batch.length}`, async () => {
    const imports = batch.map((name, index) => `import * as module${index} from 'effect@beta/${name}'`).join('\n')
    const namespaces = batch.map((_, index) => `module${index}`).join(', ')
    const session = createEsmwell({
      workerUrl: '/esmwell/worker-entry.mjs',
      autoInstall: false,
      timeoutMs: 60_000,
    })
    try {
      const result = await session.runJudge(`${imports}\nexport const solve = () => [${namespaces}].length`, [
        { name: 'module batch', exportName: 'solve', expected: batch.length },
      ])
      assert(result.ok === true, `${batch.join(', ')}: ${result.error?.message}`)
    } finally {
      session.close()
    }
  })
}
